// <auto-generated />
using System;
using CreditDeclaration.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CreditDeclaration.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250924135124_AddCredit")]
    partial class AddCredit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CreditDeclaration.Modals.Credit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Activite")
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("activite");

                    b.Property<string>("CaracteristiqueOperation")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("operation");

                    b.Property<string>("ClasseRetard")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("classe_retard");

                    b.Property<string>("CodeAgence")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("code_agence");

                    b.Property<decimal?>("CoutTotal")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("cout_total");

                    b.Property<decimal?>("CreditAccorde")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("accorde");

                    b.Property<DateTime?>("DateConstatationImpayes")
                        .HasColumnType("date")
                        .HasColumnName("date_impaye");

                    b.Property<DateTime?>("DateDeclaration")
                        .HasColumnType("date")
                        .HasColumnName("date_declaration");

                    b.Property<DateTime?>("DateExpiration")
                        .HasColumnType("date")
                        .HasColumnName("date_expiration");

                    b.Property<DateTime?>("DateLoading")
                        .HasColumnType("date")
                        .HasColumnName("date_loading");

                    b.Property<DateTime?>("DateNotation")
                        .HasColumnType("date")
                        .HasColumnName("date_notation");

                    b.Property<DateTime?>("DateOctroi")
                        .HasColumnType("date")
                        .HasColumnName("date_octroi");

                    b.Property<DateTime?>("DateRejet")
                        .HasColumnType("date")
                        .HasColumnName("date_rejet");

                    b.Property<string>("DescriptifOperation")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("descriptif_operation");

                    b.Property<string>("DureeInitiale")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("duree_initiale");

                    b.Property<string>("DureeRestante")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("duree_restante");

                    b.Property<decimal?>("Encours")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("encours");

                    b.Property<int?>("Entrepreneur")
                        .HasColumnType("int")
                        .HasColumnName("entrepreneur_id");

                    b.Property<int?>("Entreprise")
                        .HasColumnType("int")
                        .HasColumnName("entreprise_id");

                    b.Property<string>("IdentifiantPlafond")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("identifiant_plafond");

                    b.Property<decimal?>("InteretsCourus")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("interet_courus");

                    b.Property<string>("Monnaie")
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("monnaie");

                    b.Property<decimal?>("MontantCapitalNonRecouvre")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("montant_capital_nrecouvre");

                    b.Property<decimal?>("MontantGarantie")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("montant_garantie");

                    b.Property<decimal?>("MontantInteretsNonRecouvre")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("montant_interet_nrecouvre");

                    b.Property<decimal?>("MontantMensualite")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("montant_mensualite");

                    b.Property<string>("NiveauResponsabilite")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("niveau_responsabilite");

                    b.Property<decimal?>("NombreEcheancesImpayees")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("nb_echeance_impayee");

                    b.Property<string>("Notation")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("code_notation");

                    b.Property<string>("NumeroContrat")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("numero_contrat");

                    b.Property<string>("NumeroIdentiteBancaire")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("num_identite_bancaire");

                    b.Property<string>("OrganismeNotation")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("organisme_notation");

                    b.Property<int?>("Particulier")
                        .HasColumnType("int")
                        .HasColumnName("particulier_id");

                    b.Property<string>("PaysAgence")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("pays_agence");

                    b.Property<string>("Situation")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("situation");

                    b.Property<decimal?>("TauxInteret")
                        .HasColumnType("decimal(8,5)")
                        .HasColumnName("taux_interet");

                    b.Property<string>("TypeCredit")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("type_credit");

                    b.Property<string>("TypeGarantie")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("type_garantie");

                    b.Property<string>("WilayaAgence")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("wilaya_agence");

                    b.HasKey("Id");

                    b.HasIndex("Activite");

                    b.HasIndex("ClasseRetard");

                    b.HasIndex("DureeInitiale");

                    b.HasIndex("DureeRestante");

                    b.HasIndex("Entrepreneur");

                    b.HasIndex("Entreprise");

                    b.HasIndex("Monnaie");

                    b.HasIndex("NiveauResponsabilite");

                    b.HasIndex("Particulier");

                    b.HasIndex("PaysAgence");

                    b.HasIndex("Situation");

                    b.HasIndex("TypeCredit");

                    b.HasIndex("TypeGarantie");

                    b.HasIndex("WilayaAgence");

                    b.ToTable("Credit", "dbo");
                });

            modelBuilder.Entity("CreditDeclaration.Modals.PersonneMoraleAssocie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientRadicale")
                        .HasColumnType("int")
                        .HasColumnName("client_radicale");

                    b.Property<int?>("CodeAgence")
                        .HasColumnType("int")
                        .HasColumnName("code_agence");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("date")
                        .HasColumnName("date_creation");

                    b.Property<DateTime?>("DateLoading")
                        .HasColumnType("date")
                        .HasColumnName("date_loading");

                    b.Property<DateTime?>("DatePourcentage")
                        .HasColumnType("date")
                        .HasColumnName("date_pourcentage");

                    b.Property<string>("DesignationSociale")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("designation_sociale");

                    b.Property<int?>("Entreprise")
                        .HasColumnType("int")
                        .HasColumnName("entreprise_id");

                    b.Property<int?>("Fonction")
                        .HasColumnType("int")
                        .HasColumnName("fonction");

                    b.Property<string>("Identification")
                        .HasColumnType("varchar(25)")
                        .HasColumnName("identification");

                    b.Property<string>("IndicateurEtat")
                        .HasColumnType("char(1)")
                        .HasColumnName("indicateur_etat");

                    b.Property<int?>("NumSequentiel")
                        .HasColumnType("int")
                        .HasColumnName("num_sequentiel");

                    b.Property<int?>("PaysResidence")
                        .HasColumnType("int")
                        .HasColumnName("pays_residence");

                    b.Property<decimal?>("PourcentageParticipation")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("pourcentage_participation");

                    b.Property<string>("Sigle")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("sigle");

                    b.Property<int?>("TypePersonne")
                        .HasColumnType("int")
                        .HasColumnName("type_personne");

                    b.HasKey("Id");

                    b.HasIndex("Entreprise");

                    b.ToTable("Entreprise_Associe", "dbo");
                });

            modelBuilder.Entity("CreditDeclaration.Modals.PersonneMoraleDirigeant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientRadicale")
                        .HasColumnType("int")
                        .HasColumnName("client_radicale");

                    b.Property<int?>("CodeAgence")
                        .HasColumnType("int")
                        .HasColumnName("code_agence");

                    b.Property<DateTime?>("DateLoading")
                        .HasColumnType("date")
                        .HasColumnName("date_loading");

                    b.Property<int?>("Entreprise")
                        .HasColumnType("int")
                        .HasColumnName("entreprise_id");

                    b.Property<int?>("Fonction")
                        .HasColumnType("int")
                        .HasColumnName("fonction");

                    b.Property<string>("Identification")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("identification");

                    b.Property<int?>("Nationalite")
                        .HasColumnType("int")
                        .HasColumnName("Nationalite");

                    b.Property<string>("Nom")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nom");

                    b.Property<int?>("NumSequentiel")
                        .HasColumnType("int")
                        .HasColumnName("num_sequentiel");

                    b.Property<int?>("PaysResidence")
                        .HasColumnType("int")
                        .HasColumnName("pays_residence");

                    b.Property<string>("Prenom")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("prenom");

                    b.HasKey("Id");

                    b.HasIndex("Entreprise");

                    b.ToTable("Entreprise_Dirigeant", "dbo");
                });

            modelBuilder.Entity("CreditDeclaration.Modals.PersonneMoraleSociete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientRadicale")
                        .HasColumnType("int")
                        .HasColumnName("client_radicale");

                    b.Property<int?>("CodeActivite")
                        .HasColumnType("int")
                        .HasColumnName("code_activite");

                    b.Property<int?>("CodeAgence")
                        .HasColumnType("int")
                        .HasColumnName("code_agence");

                    b.Property<DateTime?>("DateLoading")
                        .HasColumnType("date")
                        .HasColumnName("date_loading");

                    b.Property<DateTime?>("DatePourcentage")
                        .HasColumnType("date")
                        .HasColumnName("date_pourcentage");

                    b.Property<string>("DesignationSocial")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("designation_social");

                    b.Property<int?>("Entreprise")
                        .HasColumnType("int")
                        .HasColumnName("entreprise_id");

                    b.Property<int?>("FormeJuridique")
                        .HasColumnType("int")
                        .HasColumnName("forme_juridique");

                    b.Property<string>("Nif")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("nif");

                    b.Property<int?>("NumSequentiel")
                        .HasColumnType("int")
                        .HasColumnName("num_sequentiel");

                    b.Property<decimal?>("PourcentageParticipation")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("pourcentage_participation");

                    b.HasKey("Id");

                    b.HasIndex("Entreprise");

                    b.ToTable("Entreprise_Societe", "dbo");
                });

            modelBuilder.Entity("CreditDeclaration.Modals.PersonnePhysique", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActeNaissance")
                        .HasColumnType("char(1)")
                        .HasColumnName("acte_naissance");

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("adresse");

                    b.Property<string>("AdresseCommune")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("adresse_commune");

                    b.Property<string>("AdresseWilaya")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("adresse_wilaya");

                    b.Property<string>("CleIntermediaire")
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("cle_intermediaire");

                    b.Property<string>("CleOnomastique")
                        .HasColumnType("nvarchar(26)")
                        .HasColumnName("cle_onomastique");

                    b.Property<string>("ClientRadical")
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("client_radical");

                    b.Property<string>("CodeAgence")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("code_agence");

                    b.Property<string>("CommuneNaissance")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("commune_naissance");

                    b.Property<DateTime?>("DateExpiration")
                        .HasColumnType("date")
                        .HasColumnName("date_expiration");

                    b.Property<DateTime?>("DateLoading")
                        .HasColumnType("date")
                        .HasColumnName("date_loading");

                    b.Property<DateTime?>("DateNaissance")
                        .HasColumnType("date")
                        .HasColumnName("date_naissance");

                    b.Property<string>("EntiteEmettrice")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("entite_emettrice");

                    b.Property<string>("EtatCivil")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("etat_civil");

                    b.Property<bool?>("Nationalite")
                        .HasColumnType("bit")
                        .HasColumnName("nationalite");

                    b.Property<string>("Nif")
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("nif");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nom");

                    b.Property<string>("NomConjoint")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nom_conjoint");

                    b.Property<string>("NomMere")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nom_mere");

                    b.Property<decimal?>("NumActeNaissance")
                        .HasColumnType("decimal(5,0)")
                        .HasColumnName("num_acte_naissance");

                    b.Property<string>("NumDoc")
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("num_doc");

                    b.Property<string>("PaysEmission")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("pays_emission");

                    b.Property<string>("PaysNaissance")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("pays_naissance");

                    b.Property<string>("Prenom")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("prenom");

                    b.Property<string>("PrenomMere")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("prenom_mere");

                    b.Property<string>("PrenomPere")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("prenom_pere");

                    b.Property<bool?>("Presume")
                        .HasColumnType("bit")
                        .HasColumnName("presume");

                    b.Property<string>("Profession")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("profession");

                    b.Property<decimal?>("Revenu")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("revenu");

                    b.Property<string>("Sexe")
                        .HasColumnType("char(1)")
                        .HasColumnName("sexe");

                    b.Property<string>("TypeDoc")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("type_doc");

                    b.Property<string>("WilayaNaissance")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("wilaya_naissance");

                    b.HasKey("Id");

                    b.HasIndex("AdresseWilaya");

                    b.HasIndex("EtatCivil");

                    b.HasIndex("PaysEmission");

                    b.HasIndex("PaysNaissance");

                    b.HasIndex("Profession");

                    b.HasIndex("TypeDoc");

                    b.HasIndex("WilayaNaissance");

                    b.HasIndex("AdresseCommune", "AdresseWilaya");

                    b.HasIndex("CommuneNaissance", "WilayaNaissance");

                    b.ToTable("Particulier", "dbo");
                });

            modelBuilder.Entity("CreditDeclaration.Models.Activite", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("code");

                    b.Property<string>("Descriptif")
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("descriptif");

                    b.Property<string>("Domaine")
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("domaine");

                    b.HasKey("Code");

                    b.ToTable("Activite", "dbo");
                });

            modelBuilder.Entity("CreditDeclaration.Models.Banque", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("code");

                    b.Property<string>("Descriptif")
                        .HasColumnType("nvarchar")
                        .HasColumnName("descriptif");

                    b.Property<string>("Domaine")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("domaine");

                    b.HasKey("Code");

                    b.ToTable("Banque", "dbo");
                });

            modelBuilder.Entity("CreditDeclaration.Models.CaracteristiqueCredit", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("code");

                    b.Property<string>("Descriptif")
                        .HasColumnType("nvarchar")
                        .HasColumnName("descriptif");

                    b.Property<string>("Domaine")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("domaine");

                    b.HasKey("Code");

                    b.ToTable("Caracteristique_Credit", "dbo");
                });

            modelBuilder.Entity("CreditDeclaration.Models.ClasseRetard", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("code");

                    b.Property<string>("Descriptif")
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descriptif");

                    b.Property<string>("Domaine")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("domaine");

                    b.HasKey("Code");

                    b.ToTable("Classe_Retard_Credit", "dbo");
                });

            modelBuilder.Entity("CreditDeclaration.Models.Commune", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("code");

                    b.Property<string>("Domaine")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("domaine");

                    b.Property<string>("Descriptif")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("descriptif");

                    b.HasKey("Code", "Domaine");

                    b.ToTable("Commune", "dbo");
                });

            modelBuilder.Entity("CreditDeclaration.Models.DureeCredit", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("code");

                    b.Property<string>("Descriptif")
                        .HasColumnType("nvarchar")
                        .HasColumnName("descriptif");

                    b.Property<string>("Domaine")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("domaine");

                    b.HasKey("Code");

                    b.ToTable("Duree_Credit", "dbo");
                });

            modelBuilder.Entity("CreditDeclaration.Models.EntitePublique", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("code");

                    b.Property<string>("Descriptif")
                        .HasColumnType("nvarchar")
                        .HasColumnName("descriptif");

                    b.Property<string>("Domaine")
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("domaine");

                    b.HasKey("Code");

                    b.ToTable("Entite_Publique", "dbo");
                });

            modelBuilder.Entity("CreditDeclaration.Models.EntrepreneurIndividuel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActeNaissance")
                        .HasColumnType("char(1)")
                        .HasColumnName("acte_naissance");

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("adresse");

                    b.Property<string>("AdresseActivite")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("adresse_activite");

                    b.Property<string>("AdresseActiviteCommune")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("adresse_activite_commune");

                    b.Property<string>("AdresseActiviteWilaya")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("adresse_activite_wilaya");

                    b.Property<string>("AdresseCommune")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("adresse_commune");

                    b.Property<string>("AdresseWilaya")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("adresse_wilaya");

                    b.Property<string>("CleIntermediaire")
                        .HasColumnType("varchar(26)")
                        .HasColumnName("cle_intermediaire");

                    b.Property<string>("CleOnomastique")
                        .HasColumnType("varchar(26)")
                        .HasColumnName("cle_onomastique");

                    b.Property<string>("ClientRadical")
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("client_radical");

                    b.Property<string>("CodeActivite")
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("code_activite");

                    b.Property<string>("CodeAgence")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("code_agence");

                    b.Property<string>("CommuneNaissance")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("commune_naissance");

                    b.Property<DateTime?>("DateExpiration")
                        .HasColumnType("date")
                        .HasColumnName("date_expiration");

                    b.Property<DateTime?>("DateLoading")
                        .HasColumnType("date")
                        .HasColumnName("date_loading");

                    b.Property<DateTime?>("DateNaissance")
                        .HasColumnType("date")
                        .HasColumnName("date_naissance");

                    b.Property<decimal?>("Effictif")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("effictif");

                    b.Property<string>("EntiteEmettrice")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("entite_emettrice");

                    b.Property<string>("EtatCivil")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("etat_civil");

                    b.Property<decimal?>("FondPropre")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("fond_propre");

                    b.Property<bool?>("Nationalite")
                        .HasColumnType("bit")
                        .HasColumnName("nationalite");

                    b.Property<string>("Nif")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("nif");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nom");

                    b.Property<string>("NomConjoint")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nom_conjoint");

                    b.Property<string>("NomMere")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nom_mere");

                    b.Property<decimal?>("NumActeNaissance")
                        .HasColumnType("decimal(5,0)")
                        .HasColumnName("num_acte_naissance");

                    b.Property<string>("NumDoc")
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("num_doc");

                    b.Property<string>("PaysEmission")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("pays_emission");

                    b.Property<string>("PaysNaissance")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("pays_naissance");

                    b.Property<string>("Prenom")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("prenom");

                    b.Property<string>("PrenomMere")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("prenom_mere");

                    b.Property<string>("PrenomPere")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("prenom_pere");

                    b.Property<bool?>("Presume")
                        .HasColumnType("bit")
                        .HasColumnName("presume");

                    b.Property<string>("Profession")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("profession");

                    b.Property<decimal?>("Recette")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("recette");

                    b.Property<decimal?>("Revenu")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("revenu");

                    b.Property<string>("Sexe")
                        .HasColumnType("char(1)")
                        .HasColumnName("sexe");

                    b.Property<decimal?>("TotalBilan")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("total_bilan");

                    b.Property<string>("TypeDoc")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("type_doc");

                    b.Property<string>("WilayaNaissance")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("wilaya_naissance");

                    b.HasKey("Id");

                    b.HasIndex("AdresseActiviteWilaya");

                    b.HasIndex("AdresseWilaya");

                    b.HasIndex("CodeActivite");

                    b.HasIndex("EtatCivil");

                    b.HasIndex("PaysEmission");

                    b.HasIndex("PaysNaissance");

                    b.HasIndex("Profession");

                    b.HasIndex("TypeDoc");

                    b.HasIndex("WilayaNaissance");

                    b.HasIndex("AdresseActiviteCommune", "AdresseActiviteWilaya");

                    b.HasIndex("AdresseCommune", "AdresseWilaya");

                    b.HasIndex("CommuneNaissance", "WilayaNaissance");

                    b.ToTable("Entrepreneur", "dbo");
                });

            modelBuilder.Entity("CreditDeclaration.Models.EtatCivil", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("code");

                    b.Property<string>("Descriptif")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("descriptif");

                    b.Property<string>("Domaine")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("domaine");

                    b.HasKey("Code");

                    b.ToTable("Etat_Civil", "dbo");
                });

            modelBuilder.Entity("CreditDeclaration.Models.FonctionDirigeant", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("code");

                    b.Property<string>("Descriptif")
                        .HasColumnType("nvarchar")
                        .HasColumnName("descriptif");

                    b.Property<string>("Domaine")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("domaine");

                    b.HasKey("Code");

                    b.ToTable("Fonction_Dirigeant", "dbo");
                });

            modelBuilder.Entity("CreditDeclaration.Models.FormeJuridique", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("code");

                    b.Property<string>("Descriptif")
                        .HasColumnType("nvarchar")
                        .HasColumnName("descriptif");

                    b.Property<string>("Domaine")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("domaine");

                    b.HasKey("Code");

                    b.ToTable("Forme_Juridique", "dbo");
                });

            modelBuilder.Entity("CreditDeclaration.Models.Monnaie", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("code_monnaie");

                    b.Property<string>("Devise")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("devise");

                    b.Property<string>("Entite")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("entite");

                    b.HasKey("Code");

                    b.ToTable("Monnaie", "dbo");
                });

            modelBuilder.Entity("CreditDeclaration.Models.NiveauResponsabilite", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("code");

                    b.Property<string>("Descriptif")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("descriptif");

                    b.Property<string>("Domaine")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("domaine");

                    b.HasKey("Code");

                    b.ToTable("Niveau_Responsabilite", "dbo");
                });

            modelBuilder.Entity("CreditDeclaration.Models.Pays", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("code");

                    b.Property<string>("Descriptif")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("descriptif");

                    b.Property<string>("Domaine")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("domaine");

                    b.HasKey("Code");

                    b.ToTable("Pays", "dbo");
                });

            modelBuilder.Entity("CreditDeclaration.Models.PersonneMorale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdresseActivite")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("adresse_activite");

                    b.Property<string>("AdresseSiege")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("adresse_siege");

                    b.Property<decimal?>("CapitalEmis")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("capital_emis");

                    b.Property<decimal?>("Capitaux")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("capitaux");

                    b.Property<decimal?>("ChiffreAffaire")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("chiffre_affaire");

                    b.Property<string>("CleIntermediaire")
                        .HasColumnType("varchar(26)")
                        .HasColumnName("cle_intermediaire");

                    b.Property<string>("CleOnomastique")
                        .HasColumnType("varchar(26)")
                        .HasColumnName("cle_onomastique");

                    b.Property<int?>("ClientRadicale")
                        .HasColumnType("int")
                        .HasColumnName("client_radicale");

                    b.Property<int?>("CodeActivitePrincipale")
                        .HasColumnType("int")
                        .HasColumnName("code_activite_principale");

                    b.Property<int?>("CodeAgence")
                        .HasColumnType("int")
                        .HasColumnName("code_agence");

                    b.Property<int?>("CommuneActivite")
                        .HasColumnType("int")
                        .HasColumnName("commune_activite");

                    b.Property<int?>("CommuneSiege")
                        .HasColumnType("int")
                        .HasColumnName("commune_siege");

                    b.Property<decimal?>("DateBilan")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("date_bilan");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("date")
                        .HasColumnName("date_creation");

                    b.Property<DateTime?>("DateExpiration")
                        .HasColumnType("date")
                        .HasColumnName("date_expiration");

                    b.Property<DateTime?>("DateLoading")
                        .HasColumnType("date")
                        .HasColumnName("date_loading");

                    b.Property<decimal?>("Effectif")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("effectif");

                    b.Property<decimal?>("Emprunt")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("emprunt");

                    b.Property<string>("EniteEmettrice")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("enite_emettrice");

                    b.Property<int?>("EntitePublique")
                        .HasColumnType("int")
                        .HasColumnName("entite_publique");

                    b.Property<decimal?>("ExcedentBrut")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("excedent_brut");

                    b.Property<int?>("FormeJuridique")
                        .HasColumnType("int")
                        .HasColumnName("forme_juridique");

                    b.Property<string>("Nif")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("nif");

                    b.Property<string>("NumDoc")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("num_doc");

                    b.Property<int?>("PaysEmission")
                        .HasColumnType("int")
                        .HasColumnName("pays_emission");

                    b.Property<decimal?>("RaportNouveau")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("raport_nouveau");

                    b.Property<decimal?>("Reserve")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("reserve");

                    b.Property<decimal?>("ResultatFinancier")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("resultat_financier");

                    b.Property<decimal?>("ResultatNet")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("resultat_net");

                    b.Property<string>("Sigle")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("sigle");

                    b.Property<decimal?>("TotalActif")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("total_actif");

                    b.Property<decimal?>("TotalBilan")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("total_bilan");

                    b.Property<int?>("TypeDoc")
                        .HasColumnType("int")
                        .HasColumnName("type_doc");

                    b.Property<decimal?>("ValeurAjoute")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("valeur_ajoute");

                    b.Property<int?>("WilayaActivite")
                        .HasColumnType("int")
                        .HasColumnName("wilaya_activite");

                    b.Property<int?>("WilayaSiege")
                        .HasColumnType("int")
                        .HasColumnName("wilaya_siege");

                    b.HasKey("Id");

                    b.ToTable("Entreprise", "dbo");
                });

            modelBuilder.Entity("CreditDeclaration.Models.Profession", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("code");

                    b.Property<string>("Descriptif")
                        .HasColumnType("text")
                        .HasColumnName("descriptif");

                    b.Property<string>("Domaine")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("domaine");

                    b.HasKey("Code");

                    b.ToTable("Profession", "dbo");
                });

            modelBuilder.Entity("CreditDeclaration.Models.SituationCredit", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("code");

                    b.Property<string>("Descriptif")
                        .HasColumnType("nvarchar")
                        .HasColumnName("descriptif");

                    b.Property<string>("Domaine")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("domaine");

                    b.HasKey("Code");

                    b.ToTable("Situation_Credit", "dbo");
                });

            modelBuilder.Entity("CreditDeclaration.Models.SourceInformationCredit", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("code");

                    b.Property<string>("Descriptif")
                        .HasColumnType("nvarchar")
                        .HasColumnName("descriptif");

                    b.Property<string>("Domaine")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("domaine");

                    b.HasKey("Code");

                    b.ToTable("Source_Information_Credit", "dbo");
                });

            modelBuilder.Entity("CreditDeclaration.Models.TypeCredit", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("code");

                    b.Property<string>("Descriptif")
                        .HasColumnType("nvarchar")
                        .HasColumnName("descriptif");

                    b.Property<string>("Domaine")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("domaine");

                    b.HasKey("Code");

                    b.ToTable("Type_Credit", "dbo");
                });

            modelBuilder.Entity("CreditDeclaration.Models.TypeDocument", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("code");

                    b.Property<string>("Descriptif")
                        .HasColumnType("nvarchar")
                        .HasColumnName("descriptif");

                    b.Property<string>("Domaine")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("domaine");

                    b.HasKey("Code");

                    b.ToTable("Type_document", "dbo");
                });

            modelBuilder.Entity("CreditDeclaration.Models.TypeGarantie", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("code");

                    b.Property<string>("Descriptif")
                        .HasColumnType("nvarchar")
                        .HasColumnName("descriptif");

                    b.Property<string>("Domaine")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("domaine");

                    b.HasKey("Code");

                    b.ToTable("Type_Garantie", "dbo");
                });

            modelBuilder.Entity("CreditDeclaration.Models.TypePersonne", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("code");

                    b.Property<string>("Descriptif")
                        .HasColumnType("nvarchar")
                        .HasColumnName("descriptif");

                    b.Property<string>("Domaine")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("domaine");

                    b.HasKey("Code");

                    b.ToTable("Type_Personne", "dbo");
                });

            modelBuilder.Entity("CreditDeclaration.Models.Wilaya", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("code");

                    b.Property<string>("Descriptif")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("descriptif");

                    b.Property<string>("Domaine")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("domaine");

                    b.HasKey("Code");

                    b.ToTable("Wilaya", "dbo");
                });

            modelBuilder.Entity("CreditDeclaration.Modals.Credit", b =>
                {
                    b.HasOne("CreditDeclaration.Models.Activite", "ActiviteData")
                        .WithMany()
                        .HasForeignKey("Activite");

                    b.HasOne("CreditDeclaration.Models.ClasseRetard", "ClasseRetardData")
                        .WithMany()
                        .HasForeignKey("ClasseRetard");

                    b.HasOne("CreditDeclaration.Models.DureeCredit", "DureeInitialeData")
                        .WithMany()
                        .HasForeignKey("DureeInitiale");

                    b.HasOne("CreditDeclaration.Models.DureeCredit", "DureeRestanteData")
                        .WithMany()
                        .HasForeignKey("DureeRestante");

                    b.HasOne("CreditDeclaration.Models.EntrepreneurIndividuel", "EntrepreneurData")
                        .WithMany()
                        .HasForeignKey("Entrepreneur");

                    b.HasOne("CreditDeclaration.Models.PersonneMorale", "EntrepriseData")
                        .WithMany()
                        .HasForeignKey("Entreprise");

                    b.HasOne("CreditDeclaration.Models.Monnaie", "MonnaieData")
                        .WithMany()
                        .HasForeignKey("Monnaie");

                    b.HasOne("CreditDeclaration.Models.NiveauResponsabilite", "NiveauResponsabiliteData")
                        .WithMany()
                        .HasForeignKey("NiveauResponsabilite");

                    b.HasOne("CreditDeclaration.Modals.PersonnePhysique", "ParticulierData")
                        .WithMany()
                        .HasForeignKey("Particulier");

                    b.HasOne("CreditDeclaration.Models.Pays", "PaysAgenceData")
                        .WithMany()
                        .HasForeignKey("PaysAgence");

                    b.HasOne("CreditDeclaration.Models.SituationCredit", "SituationData")
                        .WithMany()
                        .HasForeignKey("Situation");

                    b.HasOne("CreditDeclaration.Models.TypeCredit", "TypeCreditData")
                        .WithMany()
                        .HasForeignKey("TypeCredit");

                    b.HasOne("CreditDeclaration.Models.TypeGarantie", "TypeGarantieData")
                        .WithMany()
                        .HasForeignKey("TypeGarantie");

                    b.HasOne("CreditDeclaration.Models.Wilaya", "WilayaAgenceData")
                        .WithMany()
                        .HasForeignKey("WilayaAgence");

                    b.Navigation("ActiviteData");

                    b.Navigation("ClasseRetardData");

                    b.Navigation("DureeInitialeData");

                    b.Navigation("DureeRestanteData");

                    b.Navigation("EntrepreneurData");

                    b.Navigation("EntrepriseData");

                    b.Navigation("MonnaieData");

                    b.Navigation("NiveauResponsabiliteData");

                    b.Navigation("ParticulierData");

                    b.Navigation("PaysAgenceData");

                    b.Navigation("SituationData");

                    b.Navigation("TypeCreditData");

                    b.Navigation("TypeGarantieData");

                    b.Navigation("WilayaAgenceData");
                });

            modelBuilder.Entity("CreditDeclaration.Modals.PersonneMoraleAssocie", b =>
                {
                    b.HasOne("CreditDeclaration.Models.PersonneMorale", "EntrepriseData")
                        .WithMany()
                        .HasForeignKey("Entreprise");

                    b.Navigation("EntrepriseData");
                });

            modelBuilder.Entity("CreditDeclaration.Modals.PersonneMoraleDirigeant", b =>
                {
                    b.HasOne("CreditDeclaration.Models.PersonneMorale", "EntrepriseData")
                        .WithMany()
                        .HasForeignKey("Entreprise");

                    b.Navigation("EntrepriseData");
                });

            modelBuilder.Entity("CreditDeclaration.Modals.PersonneMoraleSociete", b =>
                {
                    b.HasOne("CreditDeclaration.Models.PersonneMorale", "EntrepriseData")
                        .WithMany()
                        .HasForeignKey("Entreprise");

                    b.Navigation("EntrepriseData");
                });

            modelBuilder.Entity("CreditDeclaration.Modals.PersonnePhysique", b =>
                {
                    b.HasOne("CreditDeclaration.Models.Wilaya", "AdresseWilayaData")
                        .WithMany()
                        .HasForeignKey("AdresseWilaya");

                    b.HasOne("CreditDeclaration.Models.EtatCivil", "EtatCivilData")
                        .WithMany()
                        .HasForeignKey("EtatCivil");

                    b.HasOne("CreditDeclaration.Models.Pays", "PaysEmissionData")
                        .WithMany()
                        .HasForeignKey("PaysEmission");

                    b.HasOne("CreditDeclaration.Models.Pays", "PaysNaissanceData")
                        .WithMany()
                        .HasForeignKey("PaysNaissance");

                    b.HasOne("CreditDeclaration.Models.Profession", "ProfessionData")
                        .WithMany()
                        .HasForeignKey("Profession");

                    b.HasOne("CreditDeclaration.Models.TypeDocument", "TypeDocData")
                        .WithMany()
                        .HasForeignKey("TypeDoc");

                    b.HasOne("CreditDeclaration.Models.Wilaya", "WilayaNaissanceData")
                        .WithMany()
                        .HasForeignKey("WilayaNaissance");

                    b.HasOne("CreditDeclaration.Models.Commune", "AdresseCommuneData")
                        .WithMany()
                        .HasForeignKey("AdresseCommune", "AdresseWilaya");

                    b.HasOne("CreditDeclaration.Models.Commune", "CommuneNaissanceData")
                        .WithMany()
                        .HasForeignKey("CommuneNaissance", "WilayaNaissance");

                    b.Navigation("AdresseCommuneData");

                    b.Navigation("AdresseWilayaData");

                    b.Navigation("CommuneNaissanceData");

                    b.Navigation("EtatCivilData");

                    b.Navigation("PaysEmissionData");

                    b.Navigation("PaysNaissanceData");

                    b.Navigation("ProfessionData");

                    b.Navigation("TypeDocData");

                    b.Navigation("WilayaNaissanceData");
                });

            modelBuilder.Entity("CreditDeclaration.Models.EntrepreneurIndividuel", b =>
                {
                    b.HasOne("CreditDeclaration.Models.Wilaya", "AdresseActiviteWilayaData")
                        .WithMany()
                        .HasForeignKey("AdresseActiviteWilaya");

                    b.HasOne("CreditDeclaration.Models.Wilaya", "AdresseWilayaData")
                        .WithMany()
                        .HasForeignKey("AdresseWilaya");

                    b.HasOne("CreditDeclaration.Models.Activite", "CodeActiviteData")
                        .WithMany()
                        .HasForeignKey("CodeActivite");

                    b.HasOne("CreditDeclaration.Models.EtatCivil", "EtatCivilData")
                        .WithMany()
                        .HasForeignKey("EtatCivil");

                    b.HasOne("CreditDeclaration.Models.Pays", "PaysEmissionData")
                        .WithMany()
                        .HasForeignKey("PaysEmission");

                    b.HasOne("CreditDeclaration.Models.Pays", "PaysNaissanceData")
                        .WithMany()
                        .HasForeignKey("PaysNaissance");

                    b.HasOne("CreditDeclaration.Models.Profession", "ProfessionData")
                        .WithMany()
                        .HasForeignKey("Profession");

                    b.HasOne("CreditDeclaration.Models.TypeDocument", "TypeDocData")
                        .WithMany()
                        .HasForeignKey("TypeDoc");

                    b.HasOne("CreditDeclaration.Models.Wilaya", "WilayaNaissanceData")
                        .WithMany()
                        .HasForeignKey("WilayaNaissance");

                    b.HasOne("CreditDeclaration.Models.Commune", "AdresseActiviteCommuneData")
                        .WithMany()
                        .HasForeignKey("AdresseActiviteCommune", "AdresseActiviteWilaya");

                    b.HasOne("CreditDeclaration.Models.Commune", "AdresseCommuneData")
                        .WithMany()
                        .HasForeignKey("AdresseCommune", "AdresseWilaya");

                    b.HasOne("CreditDeclaration.Models.Commune", "CommuneNaissanceData")
                        .WithMany()
                        .HasForeignKey("CommuneNaissance", "WilayaNaissance");

                    b.Navigation("AdresseActiviteCommuneData");

                    b.Navigation("AdresseActiviteWilayaData");

                    b.Navigation("AdresseCommuneData");

                    b.Navigation("AdresseWilayaData");

                    b.Navigation("CodeActiviteData");

                    b.Navigation("CommuneNaissanceData");

                    b.Navigation("EtatCivilData");

                    b.Navigation("PaysEmissionData");

                    b.Navigation("PaysNaissanceData");

                    b.Navigation("ProfessionData");

                    b.Navigation("TypeDocData");

                    b.Navigation("WilayaNaissanceData");
                });
#pragma warning restore 612, 618
        }
    }
}
